### ISSUE TITLE
Rework the includes for top of web pages

### ISSUE THREAD

**Issue by jennybc** [STAT545-UBC/STAT545-UBC.github.io#7]
We include our navbar with this bit of YAML in `_output.yaml`:

``` yaml
  includes:
    before_body: include/nav.html
```

Question 1: should we be using `in_header` instead of `before_body`? Look at [`_output.yaml`](https://github.com/rstudio/rmarkdown/blob/gh-pages/_output.yaml) for https://github.com/rstudio/rmarkdown which is served out of the `gh-pages` branch of https://github.com/rstudio/rmarkdown/blob/gh-pages/_output.yaml:

``` yaml
html_document:
  self_contained: false
  theme: united
  highlight: textmate
  mathjax: null
  toc_depth: 2
  lib_dir: libs
  includes:
    in_header: include/in_header.html
    before_body: include/before_body.html
    after_body: include/after_body.html
```

Question 2: I would sometimes like to include another boilerplate bit of HTML: the advice to clean out the workspace and restart R. And/or load the Gapminder data. I played around with multiple includes and with using `in_header` for the nav bar and `before_body` for the other and never really got good results (sorry that was a couple weeks ago and I forgot to take notes). I abandoned the effort but would appreciate a solution.

The file `include/clean-slate.md` holds this extra bit of info. It can be rendered as an HTML fragment to `include/clean-slate.html`. I'm about to commit a fusion I created by hand of that and `nav.html`.
